---
title: "Tidyverse Quiz"
tutorial:
  id: "com.sagrsoft.tutorials.tidyversequiz"
output: 
  learnr::tutorial:
    progressive: true
    allow_skip: true
runtime: shiny_prerendered
description: Tidyverse quiz to refresh memory.
---

```{r setup, include=FALSE}
library(learnr)
knitr::opts_chunk$set(echo = FALSE)
```


## Tibble

```{r quiz_tibble, echo=FALSE}
quiz(
  question("Which function should you use to transpose a tibble and be able to see all its columns?",
    answer("glimpse", correct = TRUE),
    answer("View"),
    answer("glance"),
    answer("peek"),
    allow_retry = TRUE,
    random_answer_order = TRUE
  ),
  question("Which function should you use to add a column to a tibble?",
    answer("add_column", correct = TRUE),
    answer("add.column"),
    answer("add_echelon"),
    answer("addColumn"),
    allow_retry = TRUE,
    random_answer_order = TRUE
  ),
  question("Which function should you use to add a row to a tibble?",
    answer("add_row", correct = TRUE),
    answer("add.row"),
    answer("add_echelon"),
    answer("addRow"),
    allow_retry = TRUE,
    random_answer_order = TRUE
  ),
  question("Which function should you use to transform a vector into a tibble?",
    answer("enframe", correct = TRUE),
    answer("make_tibble"),
    answer("create_tibble"),
    answer("fabricate_tibble"),
    allow_retry = TRUE,
    random_answer_order = TRUE
  ),
  question("Which function should you use to transform a tibble with one or two columns into a vector?",
    answer("deframe", correct = TRUE),
    answer("make_vector"),
    answer("create_vector"),
    answer("fabricate_vector"),
    allow_retry = TRUE,
    random_answer_order = TRUE
  ),
  question("Which function should you use to create a tibble from data in row-by-row layout?",
    answer("tribble", correct = TRUE),
    answer("make_tibble"),
    answer("tibble"),
    answer("create_tibble"),
    allow_retry = TRUE,
    random_answer_order = TRUE
  )
)
```

## Readr

```{r quiz_readr, echo=FALSE}
quiz(
  question("What is the name of the function that loads a comma separated values (csv) file and stores it in a tibble?",
    answer("read_csv", correct = TRUE),
    answer("read.csv"),
    answer("load_csv"),
    answer("make_tibble_from_csv"),
    allow_retry = TRUE,
    random_answer_order = TRUE
  ),
  question("What is the name of the function that loads a delimited file and stores it in a tibble?",
    answer("read_delim", correct = TRUE),
    answer("read.delim"),
    answer("load_delim"),
    answer("make_tibble_from_delim"),
    allow_retry = TRUE,
    random_answer_order = TRUE
  ),
  question("What is the name of the function that loads a file and stores it in a list of lines?",
    answer("read_lines", correct = TRUE),
    answer("read.lines"),
    answer("load_lines"),
    answer("read_file"),
    allow_retry = TRUE,
    random_answer_order = TRUE
  ),
  question("What is the name of the function that makes a tibble with a row for each token in a csv file?",
    answer("melt_csv", correct = TRUE),
    answer("dissolve_csv"),
    answer("disintegrate_csv"),
    answer("fade_csv"),
    allow_retry = TRUE,
    random_answer_order = TRUE
  ),
  question("What is the name of the function that returns the column specification for a tibble?",
    answer("spec", correct = TRUE),
    answer("specification"),
    answer("specif"),
    answer("col_spec"),
    allow_retry = TRUE,
    random_answer_order = TRUE
  ),
  question("What is the name of the function that writes a csv file from a tibble?",
    answer("write_csv", correct = TRUE),
    answer("write.csv"),
    answer("tibble_to_csv"),
    answer("compose_csv"),
    allow_retry = TRUE,
    random_answer_order = TRUE
  ),
  question("What is the name of the function that writes a list of lines to a file?",
    answer("write_lines", correct = TRUE),
    answer("write.lines"),
    answer("compose_lines"),
    answer("save_lines"),
    allow_retry = TRUE,
    random_answer_order = TRUE
  ),
  question("What are all the types of files readr can handle?",
    answer("comma separated values (csv), tab separated values (tsv), delimited, fixed width file.", correct = TRUE),
    answer("comma separated values (csv), tab separated values (tsv), delimited"),
    answer("comma separated values (csv), tab separated values (tsv)"),
    answer("tables"),
    allow_retry = TRUE,
    random_answer_order = TRUE
  )
)

```


## Dplyr

```{r quiz_dplyr, echo=FALSE}
quiz(
  question("What is the name of the function that applies a function to a set of columns inside dplyr verbs?",
    answer("across", correct = TRUE),
    answer("athwart"),
    answer("over"),
    answer("through"),
    allow_retry = TRUE,
    random_answer_order = TRUE
  ),
  question("What is the name of the function that returns a new tibble with the number of unique values in a variable?",
    answer("count", correct = TRUE),
    answer("add_count"),
    answer("tally"),
    answer("add_tally"),
    allow_retry = TRUE,
    random_answer_order = TRUE
  ),
  question("What is the name of the function that returns a new tibble with the number of unique values in a variable after you specifically group_by a variable?",
    answer("count"),
    answer("add_count"),
    answer("tally", correct = TRUE),
    answer("add_tally"),
    allow_retry = TRUE,
    random_answer_order = TRUE
  ),
  question("What is the name of the function that adds a new column named n with the number of unique values in a variable?",
    answer("count"),
    answer("add_count", correct = TRUE),
    answer("tally"),
    answer("add_tally"),
    allow_retry = TRUE,
    random_answer_order = TRUE
  ),
  question("What is the name of the function that adds a new column n with the number of unique values in a variable after you specifically group_by a variable?",
    answer("count"),
    answer("add_count"),
    answer("tally"),
    answer("add_tally", correct = TRUE),
    allow_retry = TRUE,
    random_answer_order = TRUE
  ),
  question("What function filters rows in tibble x with a match in tibble y?",
    answer("semi_join", correct = TRUE),
    answer("anti_join"),
    answer("right_join"),
    answer("inner_join"),
    allow_retry = TRUE,
    random_answer_order = TRUE     
  ),
  question("What function filters rows in tibble x without a match in tibble y?",
    answer("semi_join"),
    answer("anti_join", correct = TRUE),
    answer("right_join"),
    answer("inner_join"),
    allow_retry = TRUE,
    random_answer_order = TRUE     
  ),
  question("What function sorts a tibble by a column's values?",
    answer("arrange", correct = TRUE),
    answer("sort"),
    answer("order"),
    answer("assort"),
    allow_retry = TRUE,
    random_answer_order = TRUE 
  ),
  question("What function returns TRUE for values in a vector which are between 2 values?",
    answer("between", correct = TRUE),
    answer("inbetween"),
    answer("among"),
    answer("inside"),
    allow_retry = TRUE,
    random_answer_order = TRUE 
  ),
  question("What function combines tibbles by rows.",
    answer("bind_rows", correct = TRUE),
    answer("combine_rows"),
    answer("chain_rows"),
    answer("enchain_rows"),
    allow_retry = TRUE,
    random_answer_order = TRUE 
  ),
  question("What function combines tibbles by columns.",
    answer("bind_cols", correct = TRUE),
    answer("combine_cols"),
    answer("chain_cols"),
    answer("bind_columns"),
    allow_retry = TRUE,
    random_answer_order = TRUE 
  ),
  question("What is the name of the function that allows you to vectorise multiple if_else statements?",
    answer("case_when", correct = TRUE),
    answer("if_else"),
    answer("case-when"),
    answer("if-else"),
    allow_retry = TRUE,
    random_answer_order = TRUE        
  ),
  question("What is the name of the function that creates a vector from several vectors and fills it with the first non-missing value at each position?",
    answer("coalesce", correct = TRUE),
    answer("join"),
    answer("connect"),
    answer("fuse"),
    allow_retry = TRUE,
    random_answer_order = TRUE
  ),
  question("What function returns a vector same length as input with the cummulative mean?",
    answer("cummean", correct = TRUE),
    answer("cumavg"),
    answer("cum_mean"),
    answer("cum_avg"),
    allow_retry = TRUE,
    random_answer_order = TRUE
  ),
  question("What function returns TRUE for all cases until the first FALSE in argument?",
    answer("cumall", correct = TRUE),
    answer("cumany"),
    answer("cum_all"),
    answer("cum_any"), 
    allow_retry = TRUE,
    random_answer_order = TRUE
  ),
  question("What function returns TRUE for all cases after the first TRUE in argument?",
    answer("cumany", correct = TRUE),
    answer("cumall"),
    answer("cum_all"),
    answer("cum_any"), 
    allow_retry = TRUE,
    random_answer_order = TRUE
  ),
  question("Which ranking function ranks a vector, giving the lower rank in ties to the value that appears first?",
    answer("row_number", correct = TRUE),
    answer("min_rank"),
    answer("dense_rank"),
    answer("percent_rank"), 
    allow_retry = TRUE,
    random_answer_order = TRUE
  ),
  question("Which ranking function ranks a vector, giving the min rank to all ties?",
    answer("cume_dist"),
    answer("min_rank", correct = TRUE),
    answer("dense_rank"),
    answer("percent_rank"), 
    allow_retry = TRUE,
    random_answer_order = TRUE
  ),
  question("Which ranking function ranks a vector, giving the min rank to all ties and with no gaps between ranks?",
    answer("dense_rank", correct = TRUE),
    answer("min_rank"),
    answer("cume_dist"),
    answer("percent_rank"), 
    allow_retry = TRUE,
    random_answer_order = TRUE
  ),
  question("Which ranking function ranks a vector, giving the min rank to all ties and scaled between [0, 1]?",
    answer("percent_rank", correct = TRUE),
    answer("min_rank"),
    answer("cume_dist"),
    answer("ntile"), 
    allow_retry = TRUE,
    random_answer_order = TRUE
  ),
  question("Which ranking function ranks a vector with the proportion of values less than or equal to the current rank?",
    answer("cume_dist", correct = TRUE),
    answer("min_rank"),
    answer("ntile"),
    answer("percent_rank"), 
    allow_retry = TRUE,
    random_answer_order = TRUE
  ),
  question("Which ranking function ranks a vector by breaking it into buckets?",
    answer("ntile", correct = TRUE),
    answer("min_rank"),
    answer("cume_dist"),
    answer("percent_rank"), 
    allow_retry = TRUE,
    random_answer_order = TRUE
  ),
  question("What function selects unique rows from a tibble?",
    answer("unique"),
    answer("distinct", correct = TRUE),
    answer("singular"),
    answer("idiomatic"),
    allow_retry = TRUE,
    random_answer_order = TRUE
  ),
  question("What function subsets rows using column values?",
    answer("filter", correct = TRUE),
    answer("screen"),
    answer("strain"),
    answer("percolate"),
    allow_retry = TRUE,
    random_answer_order = TRUE
  ) 
)
```
